name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Create config.properties file
        run: |
          echo "testString=${{ secrets.TEST_STRING }}" > config.properties
          echo "baseUri=${{ secrets.BASE_URI }}" >> config.properties
          echo "oAuthKey=${{ secrets.OAUTH_KEY }}" >> config.properties

      - name: Run PetStore3 API in Docker
        run: |
          docker run -d -p 8080:8080 craynersg/petstore-api-test-project:v1.0
          sleep 10  # Wait for the API to be fully up and running

      - name: Run Tests
        run: mvn test

      - name: Clean up
        run: rm config.properties
