name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('PetStore3TestingFramework/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        working-directory: PetStore3TestingFramework
        run: mvn clean install

      - name: Run Cucumber tests
        working-directory: PetStore3TestingFramework
        run: mvn test

      - name: Archive Cucumber HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report
          path: PetStore3TestingFramework/target/testReport.html

      - name: Archive Cucumber JSON report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-json-report
          path: PetStore3TestingFramework/target/jsonReport.html
